dist: trusty
language: php
sudo: required

php:
  - 5.5

services:
  - docker

script: test -n "$TRAVIS_TAG" || { ./deploy.sh -D && ./phpunit.phar && php ./gendoc.php && ./gitci.sh "README.md" "Update README.md [skip ci]"; }
