dist: trusty
language: php
sudo: required

services:
  - docker

branches:
  except:
  - /^v\d+\.\d+(\.\d+)?(-\S*)?$/

script: ./deploy.sh -D -P && php ./gendoc.php && ./gitci.sh "README.md" "Update README.md [skip ci]"
